# Generated by Django 5.0.4 on 2024-04-09 17:44

import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=200, primary_key=True, serialize=False
                    ),
                ),
                (
                    "phone_number",
                    phone_field.models.PhoneField(blank=True, max_length=31),
                ),
                ("address", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
